# .goreleaser.yml

project_name: slurm_exporter

# Release configuration
release:
  github:
    owner: sckyzo  # Replace with your GitHub username or organization
    name: slurm_exporter
  name_template: "{{ .ProjectName }} v{{ .Version }}"

builds:
  - id: slurm_exporter
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    binary: "{{ .ProjectName }}"
    main: .
    ldflags:
      - "-s -w -X main.version={{ .Version }}"
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - bin/slurm_exporter

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

# Define signing settings (if Cosign is set up later)
signs:
  - artifacts: checksum
