version: 1

env:
  - CGO_ENABLED=0

builds:
  - binary: slurm_exporter
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
