name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - run: make test

  release:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    permissions:
      contents: write # needed to write releases
      id-token: write # needed for keyless signing
      packages: write # needed for ghcr access
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - name: Set build environment variables
        run: |
          echo "BUILD_DATE=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "GO_VERSION=$(go version)" >> $GITHUB_ENV
      - name: Debug Git State
        run: |
          echo "Current commit:"
          git log -n 1
          echo "All tags:"
          git tag -l
          echo "HEAD commit hash:"
          git rev-parse HEAD
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          BUILD_USER: "${{ github.actor }}"
          BUILD_DATE: ${{ env.BUILD_DATE }}
          GO_VERSION: ${{ env.GO_VERSION }}
          BRANCH_NAME: ${{ github.ref_name }}
          REVISION: ${{ github.sha }}

  slsa-goreleaser:
    needs: release
    permissions:
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.0.0
    with:
      go-version: 1.22
      goreleaser-version: '~> v2'
      config-path: .goreleaser.yaml
      evaluated-envs: "REVISION,BRANCH_NAME,BUILD_DATE,BUILD_USER"